<h1>Chapter 4</h1>
<h1>Introduction to Numpy Array</h1>

In [4]:
# import array
from numpy import array
#create array
l = [1.0,2.0,3.0]
a = array(l)
#display array
print(a)
#display array shape
print(a.shape)
#display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


<h2>Functions to Create Arrays</h2>

<h3>Empty</h3>

In [7]:
from numpy import empty
a = empty([3,3])
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.30427764e-321]
 [1.33511018e-306 8.34448956e-308 3.91792476e-317]]


<h3>Zeros</h3>

In [10]:
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<h3>Ones</h3>

In [13]:
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


<h2>Combining Arrays</h2>

<h3>Vertical Stack</h3>

In [15]:
#create array with vstack
from numpy import array
from numpy import vstack
#create first array
a1 = array([1,2,3])
print(a1)
#create second array
a2 = array([4,5,6])
print(a2)
#vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


<h3>Horizontal Stack</h3>

In [16]:
#create array with hstack
from numpy import array
from numpy import hstack
#create first array
a1 = array([1,2,3])
print(a1)
#create second array
a2 = array([4,5,6])
print(a2)
#vertical stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
