<h1>Chapter 4</h1>
<h1>Introduction to Numpy Array</h1>

In [2]:
# import array
from numpy import array
#create array
l = [1.0,2.0,3.0]
a = array(l)
#display array
print(a)
#display array shape
print(a.shape)
#display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


<h2>Functions to Create Arrays</h2>

<h3>Empty</h3>

In [3]:
from numpy import empty
a = empty([3,3])
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.28451502e-321]
 [1.11261162e-306 1.69119330e-306 5.98149572e-154]]


<h3>Zeros</h3>

In [4]:
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<h3>Ones</h3>

In [5]:
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


<h2>Combining Arrays</h2>

<h3>Vertical Stack</h3>

In [6]:
#create array with vstack
from numpy import array
from numpy import vstack
#create first array
a1 = array([1,2,3])
print(a1)
#create second array
a2 = array([4,5,6])
print(a2)
#vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


<h3>Horizontal Stack</h3>

In [7]:
#create array with hstack
from numpy import array
from numpy import hstack
#create first array
a1 = array([1,2,3])
print(a1)
#create second array
a2 = array([4,5,6])
print(a2)
#vertical stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


<h1>Chapter 5</h1>
<h1>Index, Slice and Reshape Numpy Arrays</h1>

<h2>From List to Arrays</h2>

<h3>One-Dimensial List to Array</h3>

In [8]:
# create one-dimensional array
from numpy import array
#list of data
data = [11,22,33,44,55]
#array of data
data  =  array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


<h2>Array Indexing</h2>

<h3>One-Dimensional Indexing</h3>

In [9]:
#index a one-dimensional array
from numpy import array
#define array
data = array([11,22,33,44,55])
#index data
print(data[0])
print(data[4])

11
55


In [10]:
#index array out of bounds 
from numpy import array
#define array
data = array([11,22,33,44,55])
#index data 
try:
    print(data[5])
except:
    print('IndexError : index is out of bounds for axis 0 with size 5')

IndexError : index is out of bounds for axis 0 with size 5


In [11]:
#negative array indexing
from numpy import array
#define array
data  = array([11,22,33,44,55])
#index data 
print(data[-1])
print(data[-5])

55
11


<h3>Two-Dimensional Indexing</h3>

In [12]:
# index two-dimensional array
from numpy import array
# define array
data = array([
    [11,22],
    [33,44],
    [55,66]
])
# index data
print(data[0,0])
print(data[0][0])

11
11


In [13]:
#index row of two-dimensional array
from numpy import array
# define array
data = array([
    [11,22],
    [33,44],
    [55,66]
])
# index data
print(data[0,])


[11 22]


<h2>Array Slicing</h2>

<h3>One-Dimnesional Slicing</h3>

In [15]:
#slice a one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data[:])

[11 22 33 44 55]


In [16]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data[0:1])

[11]


In [17]:
# negative slicing  of a one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data[-2:])

[44 55]


<h3>Two-Dimensional Slicing</h3>

In [18]:
# split input and output data 
from numpy import array 
# define array 
data = array([ [11, 22, 33], [44, 55, 66], [77, 88, 99]]) 
# separate data 
X, y = data[:, :-1], data[:, -1] 
print(X) 
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [19]:
# split train and test data 
from numpy import array 
# define array 
data = array([ [11, 22, 33], [44, 55, 66], [77, 88, 99]]) 
# separate data 
split = 2 
train,test = data[:split,:],data[split:,:] 
print(train) 
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


<h2>Array Reshaping</h2>

<h3>Data Shape</h3>

In [22]:
# shape of one-dimensional array 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55]) 
print(data.shape)

(5,)


In [23]:
# shape of a two-dimensional array 
from numpy import array 
# list of data 
data = [[11, 22], [33, 44], [55, 66]] 
# array of data 
data = array(data) 
print(data.shape)

(3, 2)


In [24]:
# row and column shape of two-dimensional array 
from numpy import array 
# list of data 
data = [[11, 22],[33, 44], [55, 66]] 
# array of data 
data = array(data) 
print('Rows: %d' % data.shape[0]) 
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [25]:
# reshape 1D array to 2D 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55]) 
print(data.shape) 
# reshape 
data = data.reshape((data.shape[0], 1)) 
print(data.shape)


(5,)
(5, 1)


<h3>Reshape 2D to 3D Array</h3>

In [27]:
#reshape 2D array to 3D
from numpy import array
#list of data
data = [[11,22],[33,44],[55,66]]
#array of data
data = array(data)
print(data.shape)
#reshape 
data = data.reshape((data.shape[0], data.shape[1],1))
print(data.shape)

(3, 2)
(3, 2, 1)


In [28]:
print(data)

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
